db:
    mongo:
        host: 192
        dbname: 'mean-dev'

bm_comments:
    facebook_api_id: '123434554'
    facebook:
         facebook_app_id: '%bm_comments.facebook_api_id%'
         active_voters:
             - bm_comments.comment_status_voter
         number_of_comments: 5
         sort_by: social
    berlingske_products:
        'Berlingske': 'Berlingske'
        'BT': 'BT'
        'Berlingske Business Magasin': 'Berlingske Business Magasin'
        'Weekendavisen': 'Weekendavisen%bm_comments.facebook_api_id%'
        "Kids' News": "Kids' News"
    access_denied_excluded_uris:
        - '/mine-sider/kundeservice'
        - '/mine-sider/kontakt-kundeservice'
        - '%bm_comments.facebook_api_id%/%bm_comments.facebook_api_id%'
        - '/mine-sider$'
    some_nested:
        nested1:
            nested2: 'some nested value %bm_comments.facebook_api_id%'
        nested_again:
          - ['%bm_comments.facebook_api_id%', '%bm_comments.facebook_api_id%']
          - '%bm_comments.facebook_api_id%'
          - 'tested'
    other_value: '%bm_comments.some_nested.nested1.nested2%'

