services:
    mongodb:
        class: AppBundle.Database.MongoDB
        arguments:
            db_host: '%db.mongo.host%'
            db_name: '%db.mongo.dbname%'
        calls:
            setPassword:
               password: '%db.mongo.dbname%'

    aws:
        class: AppBundle.AWS.Aws
        arguments:
            one: 'one param'
            two: '@mongodb'
        calls:
            setMongo:
                mongo: '@mongodb'

