services:
    json_objects:
        class: AppBundle.JsonFile
        arguments:
            file_name: '%app.json_file%'

    objects_filter:
        class: AppBundle.ObjectsFilter
        arguments:
            json_objects: '@json_objects'

    app_main:
        class: AppBundle.AppMain
        arguments:
            json_objects: '@json_objects'
            objects_filter: '@objects_filter'
