parameters:
    test_str: 'test'
    test:
        one:
            - 'arr1'
            - 'arr2'
        two:
            node1: 'test.one'
            node2:
                o1:
                    o2: '111'
                o3: '[123]'
services:
    json_objects:
        class: src.App.JsonFile
        arguments:
            file_name: '%param1%'

    file_checker:
        class: src.App.FileChecker
        calls:
            check_file:
                file_url: '@json_objects'
