services:
    json_objects:
        class: AppBundle.JsonFile
        arguments:
            file_name: '%app.json_file%'

    file_checker:
        class: AppBundle.FileChecker

    objects_filter:
        class: AppBundle.ObjectsFilter
        arguments:
            json_objects: '@json_objects'

    app_main:
        class: AppBundle.AppMain
        arguments:
            json_objects: '@json_objects'
            file_checker: '@file_checker'
            objects_filter: '@objects_filter'
